# Generated by Django 6.0.2 on 2026-03-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('aguardando', 'Aguardando Resposta'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Status'),
        ),
    ]
