# Generated by Django 6.0.2 on 2026-03-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], db_index=True, default='media', max_length=20, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('aguardando', 'Aguardando Resposta'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], db_index=True, default='aberto', max_length=20, verbose_name='Status'),
        ),
    ]
