# Generated by Django 6.0.2 on 2026-03-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_criado_em_alter_ticket_prioridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='mensagem',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem'),
        ),
    ]
