# Generated by Django 6.0.2 on 2026-03-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_comentario_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado')], db_index=True, default='aberto', max_length=20, verbose_name='Status'),
        ),
    ]
