# Generated by Django 6.0.2 on 2026-08-11 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_carregar_categorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, verbose_name='Endpoint')),
                ('p256dh', models.CharField(max_length=100, verbose_name='Chave p256dh')),
                ('auth', models.CharField(max_length=100, verbose_name='Chave auth')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Inscrição de Push',
                'verbose_name_plural': 'Inscrições de Push',
                'ordering': ['-atualizado_em'],
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
