# Generated by Django 6.0.2 on 2026-09-28 11:16

import django.db.models.deletion
import tickets.models
from django.db import migrations, models


def atribuir_nao_categorizado(apps, schema_editor):
    """Tickets com categoria NULL ganham 'Não categorizado' antes do NOT NULL."""
    Categoria = apps.get_model('tickets', 'Categoria')
    Ticket = apps.get_model('tickets', 'Ticket')
    padrao, _ = Categoria.objects.get_or_create(
        nome='Não categorizado',
        defaults={
            'icone': 'fa-tag',
            'descricao': 'Categoria padrão para chamados sem classificação.',
        },
    )
    Ticket.objects.filter(categoria__isnull=True).update(categoria=padrao)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_remover_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='tickets/comentarios/%Y/%m/', validators=[tickets.models._validate_file_mime], verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='tickets/anexos/%Y/%m/', validators=[tickets.models._validate_file_mime], verbose_name='Anexo'),
        ),
        migrations.RunPython(atribuir_nao_categorizado, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ticket',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.categoria', verbose_name='Categoria'),
        ),
    ]
